version: "3.8"
services:
  db:
    ports: 
        - "5432:5432"
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgres

  backend:
    build: ./Backend
    depends_on: 
      - db
      